language: c++
compiler: gcc
sudo: true
matrix:
  include:
    - os: osx
      compiler: clang
      env: TARGET="osx"
    - os: osx
      compiler: clang
      env: TARGET="ios"
  exclude:
    - compiler: gcc
script:
    - scripts/ci/$TARGET/build.sh
git:
    depth: 10
